### PR TITLE
Assets optimization; other minor changes.

### PR DESCRIPTION
**Pull request by RDKRACZ**
Added issues tag to the fabric.json.mod file.
Added executable permission to the gradlew file.
Losslessly compressed textures with Leanify.

### CODE REVIEW

**Review by Speechrezz — APPROVED** [review]
Thanks, definitely needed to change this!

**Review by Speechrezz — COMMENTED** [review]
What exactly did you change about the gradlew file?

**Comment by RDKRACZ** [comment]
I changed the permissions from 644 to 755 so now everyone who downloads/clones your repo can build it omitting this step on their side.
I used the chmod tool for this change and I didn't touch the windows gradlew.bat file since _I believe_ it's not needed but it could be done with Icacls tool I think.

**Comment by RDKRACZ** [comment]
I see you use Github Actions, you can see it makes gradlew exec everytime it builds you mod here https://github.com/Speechrezz/simple-graves-mod/runs/3498732774?check_suite_focus=true#step:5:1
After this change, this part is no longer needed (of course you don't need to remove it from the script)

**Review by Speechrezz — APPROVED** [review]

**Pull request merged**
